# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Cedula', models.CharField(max_length=10)),
                ('Correo', models.EmailField(blank=True, max_length=30, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Direccion', models.TextField(default='direccion', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(max_length=10)),
                ('Nombre', models.CharField(max_length=60)),
                ('Creditos', models.IntegerField(max_length=5)),
                ('Cupos', models.IntegerField(max_length=3)),
                ('EstuMatriculados', models.IntegerField(max_length=3)),
            ],
        ),
    ]
